# Generated by Django 4.2.11 on 2024-04-17 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subjectImage', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Subjects',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='courseOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseImage', models.ImageField(upload_to='images/')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDuration', models.DurationField(default=datetime.timedelta(seconds=12600), help_text='Enter the duration of the course in hours and minutes.')),
                ('coursePrice', models.IntegerField(help_text='Enter the price in dollars')),
                ('courseSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects')),
            ],
            options={
                'verbose_name': 'Courses Offered',
                'verbose_name_plural': 'Courses Offered',
            },
        ),
    ]
