# Generated by Django 4.2.11 on 2024-04-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffered',
            name='courseSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseOffered', to='home.subjects'),
        ),
    ]
